(function(g){var window=this;var Wza=function(a,b){var c=[];g.$i(b,function(a){try{var b=g.ID.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.HD(b)&&c.push(a):c.push(a)},a);
return c},Xza=function(a,b){var c=Wza(a,b);
(0,g.G)(c,function(a){g.ID.prototype.remove.call(this,a)},a)},Yza=function(){var a=g.BH;
Xza(a,a.g.Wd(!0))},O7=function(a,b){g.O0.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.R=a;this.F={};this.P(a,"onMdxReceiversChange",this.I);this.P(a,"presentingplayerstatechange",this.I);this.I()},Zza=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},$za=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},P7=function(){var a=Zza();
a&&a(!1,"No cast extension found")},Q7=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},R7=function(a){if(a>=g.Isa.length)P7();
else{var b=g.Isa[a],c="chrome-extension://"+b+g.Fsa;0<=g.i2.indexOf(b)?$za(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,Q7(c,P7)):R7(a+1)}):Q7(c,function(){R7(a+1)})}},S7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},aAa=function(){if(g.Gsa){var a=2,b=Zza(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Q7("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",P7,c)}},bAa=function(){if(S7("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){aAa();a({command:"cast.sender.init"});return}}if(!window.chrome||S7("Edge"))P7();else if(aAa(),S7("Android")&&S7("Chrome/")&&window.navigator.presentation){a="";var b=g.Nh();55<=b?a="55":50<=b&&(a="50");Q7("//www.gstatic.com/eureka/clank"+a+g.Fsa,P7)}else R7(0)},cAa=function(a){g.UG[a]&&(a=g.UG[a],(0,g.G)(a,function(a){g.SG[a]&&delete g.SG[a]}),a.length=0)},dAa=function(a){var b=g.RG();
if(b)if(b.clear(a),a)cAa(a);else for(var c in g.UG)cAa(c)},eAa=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Fg(a)||"";b&&(this.port=":"+b);this.domain=g.Eg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Xa(a,"10.0")&&(this.o=!1))},fAa=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},gAa=function(){var a=window.document.createElement("a");
g.Wc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ya(a)},hAa=function(a,b){var c=g.Ad("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Xc(c,g.$d("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},iAa=function(){var a=gAa(),b=window.document.getElementById(a),c=b&&g.gG(b,"loaded");
c||b&&!c||(b=hAa(a,function(){g.gG(b,"loaded")||(g.fG(b,"loaded","true"),g.YG(a),g.eF(g.Da(dAa,a),0))}))},jAa=function(){var a=0<=g.Hb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.JL||a},T7=function(a){g.RH("cloudview",a)},U7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},V7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},kAa=function(a,b,c,d){var e=!1;
V7()||(a=new g.SI(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.DH("yt-remote-cast-available",a);g.ZG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){T7("onReceiverSelected: "+a.friendlyName);
g.DH("yt-remote-cast-receiver",a);g.ZG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){T7("onReceiverResumed: "+a.friendlyName);
g.DH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){T7("onSessionChange: "+g.ZH(a));
a||g.FH("yt-remote-cast-receiver");g.ZG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
T7("cloudview.createSingleton_: "+e);return e},lAa=function(a){T7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},mAa=function(){T7("dispose");
var a=V7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);lAa(!1);g.WG(W7);W7.length=0},X7=function(){return!!g.EH("yt-remote-cast-installed")},nAa=function(){var a=g.EH("yt-remote-cast-receiver");
return a?a.friendlyName:null},oAa=function(){T7("clearCurrentReceiver");
g.FH("yt-remote-cast-receiver")},Y7=function(a){g.RH("cloudview",a)},pAa=function(){return X7()?V7()?V7().getCastSession():(Y7("getCastSelector: Cast is not initialized."),null):(Y7("getCastSelector: Cast API is not installed!"),null)},Z7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},$7=function(){X7()?V7()?Z7()?(T7("Requesting cast selector."),V7().requestSession()):(T7("Wait for cast API to be ready to request the session."),W7.push(g.VG("yt-remote-cast2-api-ready",$7))):Y7("requestCastSelector: Cast is not initialized."):
Y7("requestCastSelector: Cast API is not installed!")},a8=function(a,b){Z7()?V7().setConnectedScreenStatus(a,b):Y7("setConnectedScreenStatus called before ready.")},b8=function(a){T7("setCastInstalled_ "+a);
g.DH("yt-remote-cast-installed",a)},qAa=function(a,b){V7().init(a,b)},rAa=function(a,b){b8(!0);
U7(!1);qAa(a,function(a){a?(lAa(!0),g.YG("yt-remote-cast2-api-ready")):(Y7("Failed to initialize cast API."),b8(!1),g.FH("yt-remote-cast-available"),g.FH("yt-remote-cast-receiver"),mAa());b(a)})},sAa=function(a,b,c,d,e,f,k){jAa()?kAa(b,e,f,k)&&(U7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?rAa(a,c):(window.__onGCastApiAvailable=function(b,d){b?rAa(a,c):(Y7("Failed to load cast API: "+d),b8(!1),U7(!1),g.FH("yt-remote-cast-available"),g.FH("yt-remote-cast-receiver"),mAa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):iAa():bAa())):T7("Cannot initialize because not running Chrome")},d8=function(a,b){g.IG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.WB;this.A=this.o=null;this.I=(0,g.z)(this.kO,this);this.F=(0,g.z)(this.tl,this);this.G=(0,g.z)(this.jO,this);this.J=(0,g.z)(this.xO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ku,this),tAa(this))):c=3;0!=c&&(b?this.Ku(c):g.eF((0,g.z)(function(){this.Ku(c)},this),0));
var d=pAa();d&&c8(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},e8=function(a){return new g.YI(a.B.getPlayerContextData())},tAa=function(a){(0,g.G)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Da(this.BQ,a),this))},a)},uAa=function(a){(0,g.G)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},f8=function(a,b){50>a.C.Jc()&&g.YB(a.C,b)},h8=function(a,b,c){var d=e8(a);
g.aJ(d,c);-1E3!=d.g&&(d.g=b);g8(a,d)},i8=function(a,b,c){a.B.sendMessage(b,c)},g8=function(a,b){uAa(a);
a.B.setPlayerContextData(g.dJ(b));tAa(a)},c8=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.tl(null));
a.A=b;a.A&&(j8("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.tl(a.A.media[0]))},vAa=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=e8(a);b.contentId!=d.videoId&&j8("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.aJ(d,a.o.getEstimatedTime());g8(a,d)}else j8("No cast media video. Ignoring state update.")},j8=function(a){g.RH("CP",a)},k8=function(a,b,c){return(0,g.z)(function(a){this.ac("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.ac("Retrying "+b+" using MDx browser channel."),i8(this,b,c))},a)},l8=function(a){g.dI.call(this,"ScreenServiceProxy");
this.bd=a;this.o=[];this.o.push(this.bd.$_s("screenChange",(0,g.z)(this.VT,this)));this.o.push(this.bd.$_s("onlineScreenChange",(0,g.z)(this.hQ,this)))},m8=function(){return g.x("yt.mdx.remote.currentScreenId_")},n8=function(a){g.RH("remote",a)},o8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},p8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},wAa=function(){var a=p8();
if(g.Xb(a)){a=g.jI();var b=g.EH("yt-remote-session-name")||"",c=g.EH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},xAa=function(a){a?(g.DH("yt-remote-session-app",a.app),g.DH("yt-remote-session-name",a.name)):(g.FH("yt-remote-session-app"),g.FH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},q8=function(){return g.x("yt.mdx.remote.connection_")},r8=function(){var a=q8();
return!!a&&3!=a.getProxyState()},yAa=function(){return g.x("yt.mdx.remote.connectData_")},t8=function(){if(!s8){var a=g.x("yt.mdx.remote.screenService_");
s8=a?new l8(a):null}return s8},u8=function(){var a=g.kI();
if(!a)return null;var b=t8().ee();return g.cI(b,a)},v8=function(){var a=m8();
if(!a)return null;var b=t8().ee();return g.cI(b,a)},zAa=function(){var a=t8().bd.$_gos();
var b=v8();b&&q8()&&(g.bI(a,b)||a.push(b));return fAa(a)},AAa=function(){var a=zAa(),b=v8();
b||(b=u8());return g.eb(a,function(a){return b&&g.WH(b,a.key)?!0:!1})},w8=function(){var a=AAa();
!a&&X7()&&nAa()&&(a={key:"cast-selector-receiver",name:nAa()});return a},BAa=function(){var a=zAa();
X7()&&g.EH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},CAa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},y8=function(a){var b=q8();
o8(null);a||CAa("");g.ua("yt.mdx.remote.connection_",a,void 0);x8&&((0,g.G)(x8,function(b){b(a)}),x8.length=0);
b&&!a?g.ZG("yt-remote-connection-change",!1):!b&&a&&g.ZG("yt-remote-connection-change",!0)},A8=function(a,b){v8()&&v8();
CAa(a.id);var c=new g.jJ(z8,a,p8());c.connect(b,yAa());c.subscribe("beforeDisconnect",function(a){g.ZG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){q8()&&y8(null)});
y8(c)},DAa=function(){var a=u8();
a?(n8("Resume connection to: "+g.ZH(a)),A8(a,0)):(g.rI(),oAa(),n8("Skipping connecting because no session screen found."))},B8=function(){Z7()?V7().stopSession():Y7("stopSession called before API ready.");
var a=q8();a&&(a.disconnect(1),y8(null))},EAa=function(a){n8("remote.onCastSessionChange_: "+g.ZH(a));
if(a){var b=v8();b&&b.id==a.id?a8(b.id,"YouTube TV"):(b&&B8(),A8(a,1))}else q8()&&B8()},FAa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.xE("MDX_CONFIG")||b;g.BH&&Yza();g.lI();z8||(z8=new eAa(b?b.loungeApiHost:void 0),g.tI()&&(z8.g="/api/loungedev"));x8||(x8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",x8,void 0));wAa();var c=t8();if(!c){var d=new g.EI(z8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=t8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);sAa(a,d,function(a){a?m8()&&a8(m8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.ZG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),n8("Initializing: "+g.wg(b)),C8.push(g.VG("yt-remote-cast2-availability-change",function(){g.ZG("yt-remote-receiver-availability-change")})),C8.push(g.VG("yt-remote-cast2-receiver-selected",function(){o8(null);
g.ZG("yt-remote-auto-connect","cast-selector-receiver")})),C8.push(g.VG("yt-remote-cast2-receiver-resumed",function(){g.ZG("yt-remote-receiver-resumed","cast-selector-receiver")})),C8.push(g.VG("yt-remote-cast2-session-change",EAa)),C8.push(g.VG("yt-remote-connection-change",function(a){a?a8(m8(),"YouTube TV"):u8()||(a8(null,null),oAa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.MF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),n8(" -- with channel params: "+
g.wg(a)),xAa(a),c.start(),m8()||DAa())},D8=function(a,b,c){g.L.call(this);
this.D=null!=c?(0,g.z)(a,c):a;this.tc=b;this.C=(0,g.z)(this.AH,this);this.g=!1;this.o=0;this.A=this.Aa=null;this.B=[]},E8=function(a,b,c){g.L.call(this);
this.F=a;this.R=b;this.o=new g.FG(this);g.M(this,this.o);this.o.P(b,"onCaptionsTrackListChanged",this.AP);this.o.P(b,"captionschanged",this.iO);this.o.P(b,"captionssettingschanged",this.IC);this.o.P(b,"videoplayerreset",this.Ao);this.o.P(b,"mdxautoplaycancel",this.IG);this.O=this.o.P(b,"onVolumeChange",this.cB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.pB,this);c.subscribe("remotePlayerChange",this.vl,this);c.subscribe("remoteQueueChange",this.Ao,this);c.subscribe("autoplayUpNext",this.OA,
this);c.subscribe("previousNextChange",this.mB,this);c.subscribe("nowAutoplaying",this.eB,this);c.subscribe("autoplayDismissed",this.NA,this);this.suggestion=null;this.G=new g.iR(64);this.A=new g.Lt(this.DC,500,this);g.M(this,this.A);this.B=new g.Lt(this.EC,1E3,this);g.M(this,this.B);this.J=new D8(this.uT,0,this);g.M(this,this.J);this.C={};this.L=new g.Lt(this.gD,1E3,this);g.M(this,this.L);this.I=new g.Ek(this.VK,1E3,this);g.M(this,this.I);this.N=g.y;this.IC();this.Ao();this.vl()},F8=function(a,b){var c=
a.F,d=a.R.ga().lengthSeconds;
c.I=b||0;c.g.U("progresssync",b,d)},GAa=function(a){F8(a,0);
a.A.stop();G8(a,new g.iR(64))},I8=function(a,b){if(H8(a)&&!a.D){var c=null;
b&&(c={style:a.R.ri()},g.dc(c,b));a.g.vC(a.R.ga(1).videoId,c);a.C=e8(a.g).o}},J8=function(a,b){var c=a.R.Sf();
if(c){var d=c.be();var e=c.listId.toString()}var f=a.R.ga(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.sj;var m=e8(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};g.cJ(m,k,l);g.t(b)&&(g.aJ(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);i8(c,"setPlaylist",q);e||g8(c,m);G8(a,new g.iR(1))},HAa=function(a,b){if(b){var c=a.R.yc("captions","tracklist",{zy:1});
c&&c.length?(a.R.Fd("captions","track",b),a.D=!1):(a.R.jl("captions"),a.D=!0)}else a.R.Fd("captions","track",{})},H8=function(a){return e8(a.g).videoId==a.R.ga(1).videoId},G8=function(a,b){a.B.stop();
var c=a.G;if(!g.pR(c,b)){var d=g.W(b,2);d!=g.W(a.G,2)&&g.RW(a.R,d);a.G=b;IAa(a.F,c,b)}},K8=function(a){g.Y.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.CE()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.GX(this,250);g.M(this,this.o);this.A=a;this.P(a,"presentingplayerstatechange",this.B);JAa(this,g.OW(a))},JAa=function(a,b){if(3==a.A.Ra()){var c={RECEIVER_NAME:a.A.yc("remote","currentReceiver").name};
c=g.W(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.jb()||g.W(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},L8=function(a){g.zX.call(this,a);
this.A={key:g.aI(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.iR(64);this.I=0;var b=g.HW(a).G;b&&(b=b.A&&b.A.g)&&(b=new O7(a,b),g.M(this,b));b=new K8(a);g.M(this,b);g.dX(a,b.element,4)},IAa=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.vR(c,b))},M8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)B8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ga(1),e=d.videoId;if(c||e){var f=a.g.Sf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.gc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.sj,index:Math.max(a.g.Gz(),0),currentTime:0==f?void 0:f}}else c=null;n8("Connecting to: "+g.wg(b));"cast-selector-receiver"==b.key?(o8(c||null),Z7()?V7().setLaunchParams(c||null):Y7("setLaunchParams called before ready.")):!c&&
r8()&&m8()==b.key?g.ZG("yt-remote-connection-change",!0):(B8(),o8(c||null),c=t8().ee(),(c=g.cI(c,b.key))&&A8(c,1))}};
g.p(O7,g.O0);O7.prototype.I=function(){var a=this.R.yc("remote","receivers");a&&1<a.length&&!this.R.yc("remote","quickCast")?(this.F=g.Gb(a,this.B,this),g.P0(this,(0,g.H)(a,this.B)),a=this.R.yc("remote","currentReceiver"),this.kf(this.B(a)),this.enable(!0)):this.enable(!1)};
O7.prototype.B=function(a){return a.key};
O7.prototype.jf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
O7.prototype.rd=function(a){g.O0.prototype.rd.call(this,a);this.R.Fd("remote","currentReceiver",this.F[a]);this.A.Nb()};
g.h=eAa.prototype;g.h.ai=function(a){var b=this.g;if(g.t(void 0)?0:this.o)b="https://"+this.domain+this.port+this.g;return g.Og(b+a,{})};
g.h.Iu=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Fb:g.Da(this.QT,c,!0),onError:g.Da(this.PT,d),sd:g.Da(this.RT,d)};b&&(c.Pb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.uF(a,c)};
g.h.QT=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.PT=function(a,b){a(Error("Request error: "+b.status))};
g.h.RT=function(a){a(Error("request timed out"))};
var W7=[];g.A(d8,g.IG);g.h=d8.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,k8(this,"play")):i8(this,"play"),h8(this,1,g.bJ(e8(this))),this.U("remotePlayerChange")):f8(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,k8(this,"pause")):i8(this,"pause"),h8(this,2,g.bJ(e8(this))),this.U("remotePlayerChange")):f8(this,this.pause)};
g.h.pD=function(a){if(1==this.g){if(this.o){var b=e8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.jb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,k8(this,"seekTo",{newTime:a}))}else i8(this,"seekTo",{newTime:a});h8(this,3,a);this.U("remotePlayerChange")}else f8(this,g.Da(this.pD,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,k8(this,"stopVideo")):i8(this,"stopVideo");var a=e8(this);a.index=-1;a.videoId="";g.ZI(a);g8(this,a);this.U("remotePlayerChange")}else f8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=e8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){j8("set receiver volume: "+d)},this),(0,g.z)(function(){this.ac("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){j8("set receiver muted: "+b)},this),(0,g.z)(function(){this.ac("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);i8(this,"setVolume",e)}c.muted=b;c.volume=a;g8(this,c)}else f8(this,g.Da(this.setVolume,a,b))};
g.h.vC=function(a,b){if(1==this.g){var c=e8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.wg(b.style),g.dc(d,c.o));i8(this,"setSubtitlesTrack",d);g8(this,c)}else f8(this,g.Da(this.vC,a,b))};
g.h.Ju=function(a,b){if(1==this.g){i8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Pc.id});var c=e8(this);c.audioTrackId=b.Pc.id;g8(this,c)}else f8(this,g.Da(this.Ju,a,b))};
g.h.oD=function(a,b){if(1==this.g){if(a&&b){var c=e8(this);g.cJ(c,a,b);g8(this,c)}i8(this,"previous")}else f8(this,g.Da(this.oD,a,b))};
g.h.nD=function(a,b){if(1==this.g){if(a&&b){var c=e8(this);g.cJ(c,a,b);g8(this,c)}i8(this,"next")}else f8(this,g.Da(this.nD,a,b))};
g.h.Ow=function(){1==this.g?i8(this,"dismissAutoplay"):f8(this,this.Ow)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}d8.Z.dispose.call(this)};
g.h.X=function(){uAa(this);this.B=null;this.C.clear();c8(this,null);d8.Z.X.call(this)};
g.h.Ku=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.ZB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.BQ=function(a,b){this.U(a,b)};
g.h.kO=function(a){if(!a)this.tl(null),c8(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=e8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j8("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,g8(this,b)}};
g.h.tl=function(a){j8("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),vAa(this),this.U("remotePlayerChange")};
g.h.jO=function(a){a?(vAa(this),this.U("remotePlayerChange")):this.tl(null)};
g.h.xO=function(){var a=pAa();a&&c8(this,a)};
g.h.ac=function(a){g.RH("CP",a)};
g.A(l8,g.dI);g.h=l8.prototype;g.h.ee=function(a){return this.bd.$_gs(a)};
g.h.contains=function(a){return!!this.bd.$_c(a)};
g.h.get=function(a){return this.bd.$_g(a)};
g.h.start=function(){this.bd.$_st()};
g.h.add=function(a,b,c){this.bd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.bd.$_r(a,b,c)};
g.h.kp=function(a,b,c,d){this.bd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.bd.$_ubk(this.o[a]);this.o.length=0;this.bd=null;l8.Z.X.call(this)};
g.h.VT=function(){this.U("screenChange")};
g.h.hQ=function(){this.U("onlineScreenChange")};
var z8=null,x8=null,C8=[],s8=null;g.A(D8,g.L);g.h=D8.prototype;g.h.zH=function(a){this.B=arguments;this.g=!1;this.Aa?this.A=(0,g.F)()+this.tc:this.Aa=g.qg(this.C,this.tc)};
g.h.stop=function(){this.Aa&&(g.rg(this.Aa),this.Aa=null);this.A=null;this.g=!1;this.B=[]};
g.h.pause=function(){++this.o};
g.h.resume=function(){this.o&&(--this.o,!this.o&&this.g&&(this.g=!1,this.D.apply(null,this.B)))};
g.h.X=function(){this.stop();D8.Z.X.call(this)};
g.h.AH=function(){this.A?(this.Aa=g.qg(this.C,this.A-(0,g.F)()),this.A=null):(this.Aa=null,this.o?this.g=!0:(this.g=!1,this.D.apply(null,this.B)))};g.p(E8,g.L);g.h=E8.prototype;
g.h.X=function(){g.L.prototype.X.call(this);this.A.stop();this.B.stop();this.J.stop();this.N();this.g.unsubscribe("proxyStateChange",this.pB,this);this.g.unsubscribe("remotePlayerChange",this.vl,this);this.g.unsubscribe("remoteQueueChange",this.Ao,this);this.g.unsubscribe("autoplayUpNext",this.OA,this);this.g.unsubscribe("previousNextChange",this.mB,this);this.g.unsubscribe("nowAutoplaying",this.eB,this);this.g.unsubscribe("autoplayDismissed",this.NA,this);this.g=this.F=null};
g.h.xz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(H8(this)){if(1081!=e8(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":e8(this.g).jb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.gj(c[0],c[1]);break;case "control_subtitles_set_track":I8(this,c[0]);break;case "control_set_audio_track":c=c[0],H8(this)&&this.g.Ju(this.R.ga(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.R.getCurrentTime();J8(this,0==c?void 0:c);break;case "control_seek":J8(this,c[0]);break;case "control_subtitles_set_track":I8(this,c[0]);break;case "control_set_audio_track":c=c[0],H8(this)&&this.g.Ju(this.R.ga(1).videoId,c)}};
g.h.iO=function(a){this.J.zH(a)};
g.h.uT=function(a){this.xz("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.IC=function(){var a=this.R.yc("captions","track");g.Xb(a)||I8(this,a)};
g.h.cB=function(a){if(H8(this)){this.g.unsubscribe("remotePlayerChange",this.vl,this);var b=Math.round(a.volume);a=!!a.muted;var c=e8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.L.start();this.g.subscribe("remotePlayerChange",this.vl,this)}};
g.h.AP=function(){g.Xb(this.C)||HAa(this,this.C);this.D=!1};
g.h.pB=function(a,b){this.B.stop();2==b&&this.EC()};
g.h.vl=function(){if(H8(this)){this.A.stop();var a=e8(this.g);switch(a.g){case 1081:case 1:G8(this,new g.iR(8));this.DC();break;case 1085:case 3:G8(this,new g.iR(9));break;case 1083:case 0:G8(this,new g.iR(2));this.I.stop();F8(this,this.R.ga().lengthSeconds);break;case 1084:G8(this,new g.iR(4));break;case 2:G8(this,new g.iR(4));F8(this,g.bJ(a));break;case -1:G8(this,new g.iR(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},G8(this,new g.iR(128,a))}a=e8(this.g).o;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,HAa(this,a));a=e8(this.g);-1==a.volume||Math.round(this.R.getVolume())==a.volume&&this.R.isMuted()==a.muted||this.L.isActive()||this.gD()}else GAa(this)};
g.h.mB=function(){this.R.U("mdxpreviousnextchange")};
g.h.Ao=function(){H8(this)||GAa(this)};
g.h.IG=function(){this.g.Ow()};
g.h.OA=function(a){a&&(a=g.uF("/watch_queue_ajax",{method:"GET",Yc:{action_get_watch_queue_item:1,video_id:a},Fb:(0,g.z)(this.AR,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.AR=function(a,b){var c=new g.jQ({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.R.U("mdxautoplayupnext",c)};
g.h.eB=function(a){(0,window.isNaN)(a)||this.R.U("mdxnowautoplaying",a)};
g.h.NA=function(){this.R.U("mdxautoplaycanceled")};
g.h.VK=function(a,b){-1==e8(this.g).g?J8(this,a):b&&this.g.pD(a)};
g.h.gD=function(){if(H8(this)){var a=e8(this.g);this.o.Da(this.O);a.muted?this.R.mute():this.R.Tf();this.R.setVolume(a.volume);this.O=this.o.P(this.R,"onVolumeChange",this.cB)}};
g.h.DC=function(){this.A.stop();if(!this.g.ka()){var a=e8(this.g);a.jb()&&G8(this,new g.iR(8));F8(this,g.bJ(a));this.A.start()}};
g.h.EC=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(K8,g.Y);K8.prototype.B=function(a){JAa(this,a.state)};g.p(L8,g.zX);g.h=L8.prototype;g.h.create=function(){FAa(g.pO(g.X(this.g)));this.D.push(g.VG("yt-remote-before-disconnect",this.eO,this));this.D.push(g.VG("yt-remote-connection-change",this.KQ,this));this.D.push(g.VG("yt-remote-receiver-availability-change",this.nB,this));this.D.push(g.VG("yt-remote-auto-connect",this.IQ,this));this.D.push(g.VG("yt-remote-receiver-resumed",this.HQ,this));this.nB()};
g.h.load=function(){this.g.oq();g.zX.prototype.load.call(this);this.C=new E8(this,this.g,this.o);var a=(a=yAa())?a.currentTime:0;var b=r8()?new d8(q8(),void 0):null;0==a&&b&&(a=g.bJ(e8(b)));0!=a&&(this.I=a||0,this.g.U("progresssync",a,void 0));IAa(this,this.F,this.F);g.J1(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.We(this.C,this.o);this.o=this.C=null;g.zX.prototype.unload.call(this);g.J1(this.g.app,5)};
g.h.X=function(){g.WG(this.D);g.zX.prototype.X.call(this)};
g.h.Zk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.xz.apply(this.C,[].concat([a],g.pa(c)))};
g.h.vH=function(){return this.loaded?this.C.suggestion:null};
g.h.If=function(){return this.o?e8(this.o).If:!1};
g.h.hasNext=function(){return this.o?e8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.yK=function(){var a=e8(this.o),b=this.g.ga();return{allowSeeking:this.g.cd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+g.$I(a):a.B,isPeggedToLive:1>=(a.D?a.A+g.$I(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+g.$I(a):a.A,seekableStart:0<a.C?a.C+g.$I(a):a.C}};
g.h.zK=function(){this.o&&this.o.nD()};
g.h.AK=function(){this.o&&this.o.oD()};
g.h.eO=function(a){1==a&&(this.J=this.o?e8(this.o):null)};
g.h.KQ=function(){var a=r8()?new d8(q8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ve(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.ga().videoId&&this.g.Ez(a.videoId,g.bJ(a)));this.g.U("videodatachange","newdata",this.g.ga(),3)};
g.h.nB=function(){this.G=[this.A].concat(BAa());var a=w8()||this.A;M8(this,a);this.g.va("onMdxReceiversChange")};
g.h.IQ=function(){var a=w8();M8(this,a)};
g.h.HQ=function(){this.B=w8()};
g.h.xK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?$7():M8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&$7(),!0):!1}};
g.h.BK=function(){i8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.ud=function(){return!1};g.SZ.remote=L8;})(_yt_player);
